print('-' * 35)
print('Tugas 1 SISOP Kelas-B')
print('-' * 35)
print('Nama: Zulfaz Refie Ababil')
print('NPM : 21083010122')
print('-' * 35)
print('notes:')
print('-' * 35)
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
