print('-------------------------------------------')
print('Tugas 1 SISOP Kelas - B')
print('-------------------------------------------')
print('Nama:Zulfaz Refie Ababil')
print('MPM : 21083010122')
print('-------------------------------------------')
print('notes:')
print('-------------------------------------------')
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
